# Generated by Django 5.2.3 on 2025-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctor_avg_slot_minutes'),
        ('queuezero', '0002_token_qr_image_alter_token_doctor_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='token',
            name='is_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('served', 'Served')], default='waiting', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('doctor', 'token_number')},
        ),
    ]
