# Generated by Django 5.2.7 on 2025-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuezero', '0003_alter_token_options_token_is_called_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pre_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
