# Generated by Django 5.2.6 on 2025-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
