# Generated by Django 5.2.3 on 2025-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_department_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg_slot_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
